import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
  },
  headerBar: {
    height: 144,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    position: 'relative',
  },
  roiIconContainer: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    width: 110,
    height: 110,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roiIcon: {
    width: 110,
    height: undefined,
    aspectRatio: 1,
    resizeMode: 'contain',
  },
  bottomButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#FBF9F9',
    height: 66,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginHorizontal: 5,
    width: 150,
    height: 50,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  buttonText: {
    fontFamily: 'Trebuchet MS',
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  detailsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  tile: {
    backgroundColor: '#FBF9F9',
    padding: 15,
    marginVertical: 10,
    borderRadius: 5,
    alignItems: 'flex-start',
    width: '98%',
    marginLeft: '1%',
    marginRight: '1%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  tileText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    textAlign: 'left',
    width: '100%',
  },
  editButton: {
    position: 'absolute',
    right: 10,
    top: 0,
    backgroundColor: '#941a1d',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    width: 70,
  },
  editButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  picker: {
    height: 60,
    width: '100%',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 10,
  },
    settingsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  settingsContent: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  iconContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  icon: {
    width: 65,
    height: 65,
    marginBottom: 10,
  },
  iconTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
});
